plugins {
    id 'io.github.qigao.simpledsl.android'
}

simpledsl {
    androidLibrary {
        namespace = 'example.feature'
    }
    jetpackCompose()
    capability('ksp')
}

assert pluginManager.hasPlugin('com.google.devtools.ksp')
assert !pluginManager.hasPlugin('org.jetbrains.kotlin.android')
assert configurations.findByName('ksp') != null
